server:
  port: 9999
magic-api:
  web: /magic/web
  resource:
    type: database
    table-name: magic_api_file_v2
  backup:
    enable: true
    table-name: magic_backup_record_v2
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/magic?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
